name: Triangle Land
markdown: kramdown
pygments: true
url: http://le717.github.io
baseurl: ""
wp_url: //Triangle717.WordPress.com
gems:
 - jekyll-mentions
 - jekyll-redirect-from
 - jekyll-sitemap
 - jemoji
#sass:
#    style: :compressed
