name: Triangle Land
markdown: kramdown
highlighter: pygments
baseurl: ""

author_wp: http://Triangle717.WordPress.com
author_twitter: https://twitter.com/_le717
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

sass:
  style: :compressed
  sass_dir: css/
