name: Triangle Land
markdown: kramdown
highlighter: null
baseurl: ""

wpurl: http://Triangle717.WordPress.com
gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

sass:
  style: :compressed
  sass_dir: css/
